version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      - default
      - link
    ports:
      - '8080:80'
    volumes:
      - './vhost.d/:/etc/nginx/vhost.d/'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

  # main:
    # build: ./src
    # depends_on:
      # - nginx-proxy
    # ports:
      # - "8181:5000"
    # networks:
      # - default

  db:
    image:
      mariadb:latest
    volumes:
      - dbdata:/var/lib/mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=diaries'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=root'

  link:
    build: ./link
    depends_on:
      - nginx-proxy
      - db
    ports:
      - "8182:5000"
    networks:
      - link

networks:
  default:
    external:
      name: nginx-net
  link:
    external:
      name: nginx-link

volumes:
  dbdata:
