version: '2'

services:

  db:
    image:
      mariadb:latest
    networks:
      - default
    volumes:
      - dbdata:/var/lib/mariadb
    restart: always
    ports:
      - "3306:8080"
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=diaries'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=root'

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      - default
    ports:
      - '8080:80'
    volumes:
      - './vhost.d/:/etc/nginx/vhost.d/'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

  main:
    build: ./src
    restart: always
    depends_on:
      - nginx-proxy
    ports:
      - "8081:5000"
    networks:
      - default

  link:
    build: ./link
    restart: always
    links:
      - db
    depends_on:
      - nginx-proxy
      - db
    ports:
      - "8082:5000"
    networks:
      - default

networks:
  default:
    external:
      name: nginx-net
  # link:
    # external:
      # name: nginx-link

volumes:
  dbdata:
