version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      - default
      - link
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './vhost.d/:/etc/nginx/vhost.d/'
      - '/usr/share/nginx/html'
      - './certs:/etc/nginx/certs:ro'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    volumes:
      - './certs:/etc/nginx/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    volumes_from:
      - nginx-proxy

  main:
    build: ./src
    depends_on:
      - nginx-proxy
    ports:
      - "8181:5000"
    networks:
      - default
    environment:
      - 'LETSENCRYPT_EMAIL=shutdown57@riseup.net'
      - 'LETSENCRYPT_HOST=devdiaries.ml'
      - 'VIRTUAL_HOST=devdiaries.ml'

  db:
    image:
      mariadb:latest
    volumes:
      - dbdata:/var/lib/mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=diaries'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=root'

  link:
    build: ./link
    depends_on:
      - nginx-proxy
      - db
    ports:
      - "8182:5000"
    networks:
      - link
    environment:
      - 'LETSENCRYPT_EMAIL=shutdown57@riseup.net'
      - 'LETSENCRYPT_HOST=link.devdiaries.ml'
      - 'VIRTUAL_HOST=link.devdiaries.ml'

networks:
  default:
    external:
      name: nginx-net
  link:
    external:
      name: nginx-link

volumes:
  dbdata:
