version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      - default
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './vhost.d/:/etc/nginx/vhost.d/'
      - '/usr/share/nginx/html'
      - './certs:/etc/nginx/certs:ro'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    volumes:
      - './certs:/etc/nginx/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    volumes_from:
      - nginx-proxy

  main:
    build: ./src
    restart: always
    links:
      - db
    depends_on:
      - nginx-proxy
    networks:
      - default
    environment:
      - 'LETSENCRYPT_EMAIL=shutdown57@riseup.net'
      - 'LETSENCRYPT_HOST=devdiaries.xyz'
      - 'VIRTUAL_HOST=devdiaries.xyz'

  db:
    image:
      mariadb:latest
    networks:
      - default
    volumes:
      - dbdata:/var/lib/mariadb
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=diaries'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=root'

  link:
    build: ./link
    restart: always
    links:
      - db
    depends_on:
      - nginx-proxy
      - db
    networks:
      - default
    environment:
      - 'LETSENCRYPT_EMAIL=shutdown57@riseup.net'
      - 'LETSENCRYPT_HOST=link.devdiaries.xyz'
      - 'VIRTUAL_HOST=link.devdiaries.xyz'

networks:
  default:
    external:
      name: nginx-net

volumes:
  dbdata:
